# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Trigger Jenkins Jobs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    #runs-on: ${{ matrix.os }}
    runs-on: self-hosted
    #strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      #fail-fast: false
      #matrix:
        #os: [macos-latest, macos-14.1, macos-14.5]

    steps:
      - name: Install jq
        run: brew install jq
        
      - name: Get Jenkins Crumb
        id: get-crumb
        run: |
          echo "Fetching Jenkins Crumb..."
          CRUMB=$(curl -u ${{ vars.JENKINS_USER}}:${{ vars.JENKINS_API_TOKEN }} "${{ vars.JENKINS_URL }}/crumbIssuer/api/json" | jq -r .crumb)
          echo "Crumb: $CRUMB"
          echo "::set-output name=crumb::$CRUMB"
          
      - name: Trigger Jenkins Jobs
        run: |
          curl -X POST ${{ vars.JENKINS_URL }}/job/${{ vars.JENKINS_JOB_NAME }}/buildWithParameters \
            --user ${{ vars.JENKINS_USER}}:${{ vars.JENKINS_API_TOKEN }} \
            -H Jenkins-Crumb:$CRUMB

